name: Actions after commit
run-name: Running appropriate tests after committing changes
on: push
jobs:
  test_biotsavart:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
