name: Actions after commit
run-name: Running appropriate tests after committing changes
on: push
jobs:
  test_biotsavart:
    runs-on: windows-2022
    steps:
      - run: python --version
      - run: cd ../../
      - run: ls